/**
 * Semantic color classes. Components import `ui` — never write palette
 * utilities (`bg-accent`, `text-fg`, hex) inline.
 */
export const ui = {
  page: 'bg-canvas text-fg',
  sidebar:
    'fixed inset-y-0 left-0 z-20 flex flex-col border-r border-line bg-canvas',
  sidebarHeader: 'shrink-0 border-b border-line',
  sidebarService: 'shrink-0 border-b border-line',
  sidebarMenu: 'min-h-0 flex-1 overflow-y-auto',
  sidebarFooter: 'shrink-0 border-t border-line',
  brand: 'text-accent',
  eyebrow: 'text-fg-subtle',
  title: 'text-fg',
  body: 'text-fg-muted',
  accentText: 'text-accent-hover',
  dangerText: 'text-danger',
  caption: 'text-fg-subtle',
  navActive: 'bg-accent-soft text-accent-hover',
  navIdle: 'text-fg-muted hover:bg-surface-muted hover:text-fg',
  card: 'border border-line bg-surface',
  panel: 'flex min-h-0 min-w-0 flex-col bg-surface',
  panelSplit: 'border-r border-line',
  workbench: 'grid h-svh min-h-0 grid-cols-[minmax(280px,360px)_minmax(0,1fr)]',
  workbenchResponsive:
    'grid h-svh min-h-0 grid-cols-1 grid-rows-2 xl:grid-cols-[minmax(280px,360px)_minmax(0,1fr)] xl:grid-rows-1',
  tabList: 'flex shrink-0 gap-1',
  tabActive: 'border-b-2 border-accent text-accent-hover',
  tabIdle: 'text-fg-muted hover:text-fg',
  code: 'bg-control font-mono text-[12px] leading-5 text-fg',
  codeGutter: 'select-none text-right text-fg-subtle',
  rail: 'shadow-[inset_3px_0_0_0_var(--color-accent)]',
  hairline: 'border-line',
  hairlineT: 'border-t border-line',
  hairlineB: 'border-b border-line',
  tableHead: 'bg-surface-muted text-fg-subtle',
  tableRow: 'border-t border-line hover:bg-surface-muted',
  tableCell: 'text-fg-muted',
  tableCellStrong: 'text-fg',
  control:
    'h-9 w-full rounded-md border border-line bg-control px-3 text-[14px] text-fg outline-none transition-[border-color,box-shadow] duration-150 ease-[cubic-bezier(0.23,1,0.32,1)] placeholder:text-fg-subtle focus:border-accent focus:shadow-[inset_0_0_0_1px_var(--color-accent)] disabled:cursor-not-allowed disabled:text-fg-subtle',
  controlInvalid:
    'border-danger focus:border-danger focus:shadow-[inset_0_0_0_1px_var(--color-danger)]',
  dropdownPanel:
    'absolute z-20 mt-1 max-h-60 w-full overflow-auto rounded-md border border-line bg-surface py-1 shadow-[inset_3px_0_0_0_var(--color-accent)]',
  dropdownValue: 'text-fg',
  dropdownPlaceholder: 'text-fg-subtle',
  dropdownChevron: 'shrink-0 text-fg-subtle transition-transform duration-150',
  dropdownOptionActive: 'bg-surface-muted text-fg',
  dropdownOptionIdle: 'text-fg-muted',
  check: 'text-accent',
  buttonPrimary:
    'bg-accent text-on-accent hover:bg-accent-hover disabled:bg-accent/40',
  buttonGhost:
    'border border-line bg-surface text-fg hover:border-accent hover:text-accent-hover disabled:text-fg-subtle',
  modal: 'fixed inset-0 m-auto max-h-[calc(100svh-2rem)] w-[min(100%-2rem,32rem)] overflow-y-auto rounded-lg border border-line bg-surface p-0 text-fg shadow-[0_12px_32px_color-mix(in_oklab,var(--color-fg)_18%,transparent)] backdrop:bg-fg/20',
  choiceIdle: 'border border-line bg-surface text-fg-muted hover:border-accent',
  choiceActive: 'border border-accent bg-accent-soft text-accent-hover',
  spinner: 'animate-spin text-accent',
  emptyIcon: 'mx-auto text-accent',
  badgeSuccess: 'bg-accent-soft text-accent-hover',
  badgeWarning: 'bg-warning-soft text-warning',
  badgeDanger: 'bg-danger-soft text-danger',
  badgeMuted: 'bg-surface-muted text-fg-muted',
  toastFrame: 'border border-line bg-surface',
  toastPendingRail: 'shadow-[inset_3px_0_0_0_var(--color-accent)]',
  toastSuccessRail: 'shadow-[inset_3px_0_0_0_var(--color-success)]',
  toastErrorRail: 'shadow-[inset_3px_0_0_0_var(--color-danger)]',
  toastBarTrack: 'bg-line',
  toastBarPending: 'bg-accent',
  toastBarSuccess: 'bg-success',
  toastBarError: 'bg-danger',
  toastIconPending: 'animate-spin text-accent',
  toastIconSuccess: 'text-success',
  toastIconError: 'text-danger',
  skeleton: 'bg-surface-muted',
  progressTrack: 'bg-line',
  progressFill: 'bg-accent',
  progressFailed: 'bg-danger',
  diagramLane: 'fill-canvas',
  diagramLaneFault: 'fill-danger-soft',
  diagramIdle: 'fill-surface stroke-line [stroke-width:1.5px]',
  diagramPending: 'fill-warning-soft stroke-warning [stroke-width:1.5px]',
  diagramSuccess: 'fill-accent-soft stroke-accent [stroke-width:1.75px]',
  diagramFailed: 'fill-danger-soft stroke-danger [stroke-width:1.75px]',
  diagramSkipped: 'fill-surface-muted stroke-line [stroke-width:1.25px] opacity-40',
  diagramEdgeIdle: 'fill-none stroke-line [stroke-width:1.5px]',
  diagramEdgePending: 'fill-none stroke-warning [stroke-width:1.75px]',
  diagramEdgeSuccess: 'fill-none stroke-accent [stroke-width:1.75px]',
  diagramEdgeFailed: 'fill-none stroke-danger [stroke-width:1.75px]',
  diagramEdgeSkipped: 'fill-none stroke-line [stroke-width:1.25px] opacity-30',
}
