export const studentUi = {
  page: 'min-h-svh overflow-x-hidden bg-student-canvas font-student-sans text-student-ink',
  shell: 'mx-auto flex min-h-svh w-full max-w-6xl flex-col px-4 py-4 sm:px-6 sm:py-6',
  topbar: 'mb-8 grid grid-cols-[1fr_auto] items-center gap-2 sm:min-h-11 sm:grid-cols-[1fr_auto_1fr] sm:gap-4',
  topbarCompact: 'flex justify-between',
  headerAction: 'justify-self-end',
  brand: 'font-student-display text-lg font-bold tracking-tight text-student-primary-strong',
  brandMark: 'grid size-10 place-items-center rounded-2xl bg-student-primary text-white',
  skipLink: 'sr-only cursor-pointer rounded-xl bg-student-primary px-4 py-2 font-semibold text-white focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-10 focus-visible:ring-4 focus-visible:ring-student-primary/20',
  title: 'font-student-display text-3xl font-bold tracking-[-0.03em] text-student-ink sm:text-4xl',
  eyebrow: 'font-student-display text-sm font-semibold text-student-primary',
  body: 'text-[15px] leading-6 text-student-muted',
  caption: 'text-[13px] leading-5 text-student-subtle',
  card: 'rounded-3xl border border-student-line bg-student-surface shadow-[0_14px_36px_-22px_rgba(49,46,129,0.42)]',
  cardMuted: 'rounded-3xl border border-student-line bg-student-surface-muted/50',
  buttonPrimary: 'bg-student-primary text-white hover:bg-student-primary-strong focus-visible:ring-student-primary',
  buttonBookmark: 'bg-student-bookmark text-student-ink hover:bg-student-bookmark/85 focus-visible:ring-student-bookmark',
  buttonQuiet: 'bg-student-surface text-student-primary-strong hover:bg-student-surface-muted focus-visible:ring-student-primary',
  control: 'student-control min-h-11 w-full rounded-2xl border border-student-line bg-student-control px-3.5 text-[16px] text-student-ink outline-none transition-[border-color,box-shadow] duration-150 placeholder:text-student-subtle focus:border-student-primary focus-visible:ring-4 focus-visible:ring-student-primary/15 disabled:cursor-not-allowed disabled:opacity-60',
  controlInvalid: 'border-student-danger focus:border-student-danger focus-visible:ring-student-danger/15',
  label: 'font-student-display text-sm font-semibold text-student-ink',
  error: 'text-sm font-medium text-student-danger',
  link: 'cursor-pointer font-semibold text-student-primary underline decoration-student-primary/30 underline-offset-4 hover:decoration-student-primary',
  complete: 'bg-student-complete/12 text-student-complete',
  current: 'bg-student-primary/12 text-student-primary-strong',
  next: 'bg-student-bookmark/18 text-student-ink',
  emptyIcon: 'grid size-12 place-items-center rounded-2xl bg-student-bookmark/18 text-student-ink',
  emptyTitle: 'font-student-display text-xl font-bold text-student-ink',
  loadingIcon: 'text-student-primary',
  progressRing: 'grid size-24 place-items-center rounded-full border-8 border-student-primary/15 bg-student-surface',
  progressValue: 'font-student-display text-2xl font-bold text-student-primary-strong',
  trailItem: 'flex items-center gap-3 rounded-2xl border border-student-line bg-student-surface px-4 py-3',
  trailTitle: 'truncate font-student-display text-sm font-bold text-student-ink',
  accountTrigger: 'student-press flex min-h-11 max-w-44 cursor-pointer list-none items-center gap-2 rounded-2xl border border-student-line bg-student-surface py-1.5 pr-2 pl-1.5 text-left outline-none hover:bg-student-surface-muted focus-visible:ring-4 focus-visible:ring-student-primary/15 sm:max-w-56 [&::-webkit-details-marker]:hidden',
  accountAvatar: 'grid size-8 shrink-0 place-items-center rounded-xl bg-student-primary text-xs font-bold text-white',
  accountName: 'truncate font-student-display text-sm font-bold text-student-ink',
  accountRole: 'truncate text-xs text-student-muted',
  accountChevron: 'shrink-0 text-student-muted transition-transform duration-150 group-open:rotate-180',
  accountMenu: 'student-menu-enter absolute top-[calc(100%+0.5rem)] right-0 z-20 grid min-w-56 overflow-hidden rounded-2xl border border-student-line bg-student-surface p-1.5 shadow-[0_18px_40px_-18px_rgba(49,46,129,0.45)]',
  accountMenuLink: 'student-press flex min-h-11 cursor-pointer items-center gap-3 rounded-xl px-3 text-sm font-semibold text-student-ink outline-none hover:bg-student-surface-muted focus-visible:ring-4 focus-visible:ring-student-primary/15',
  accountMenuIcon: 'text-student-primary',
  accountLogoutIcon: 'text-student-danger',
  navigation: 'col-span-2 col-start-1 row-start-2 flex items-center justify-center gap-1 justify-self-center rounded-2xl border border-student-line bg-student-surface p-1 shadow-[0_8px_20px_-16px_rgba(49,46,129,0.5)] sm:col-span-1 sm:col-start-auto sm:row-start-auto',
  navigationLink: 'student-press inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-xl px-3 text-sm font-semibold text-student-muted outline-none hover:bg-student-surface-muted hover:text-student-primary-strong focus-visible:ring-4 focus-visible:ring-student-primary/15',
  navigationLinkActive: 'bg-student-primary text-white hover:bg-student-primary hover:text-white',
  courseCard: 'group grid cursor-pointer overflow-hidden rounded-3xl border border-student-line bg-student-surface shadow-[0_14px_36px_-22px_rgba(49,46,129,0.42)] outline-none transition-shadow duration-200 hover:shadow-[0_20px_42px_-20px_rgba(49,46,129,0.5)] focus-visible:ring-4 focus-visible:ring-student-primary/15',
  courseThumbnail: 'relative aspect-video overflow-hidden bg-student-surface-muted',
  courseThumbnailFallback: 'grid aspect-video place-items-center bg-student-surface-muted text-student-subtle',
  courseThumbnailOverlay: 'absolute inset-0 z-10 grid place-items-center bg-student-surface-muted/85 text-student-primary',
  courseThumbnailImage: 'h-full w-full object-cover',
  courseMeta: 'text-xs font-bold tracking-[0.12em] uppercase text-student-primary',
  courseTitle: 'line-clamp-2 font-student-display text-xl font-bold leading-6 text-student-ink',
  courseHint: 'line-clamp-1 text-sm text-student-muted',
  courseProgressLabel: 'text-xs font-semibold text-student-muted',
  courseProgressValue: 'font-student-display text-sm font-bold text-student-primary-strong',
  progressTrack: 'h-2 overflow-hidden rounded-full bg-student-primary/15',
  progressFill: 'block h-full origin-left rounded-full bg-student-primary transition-transform duration-200 ease-out',
  courseFooter: 'flex items-center justify-between gap-3 border-t border-student-line pt-3',
  courseFooterText: 'inline-flex min-w-0 items-center gap-1.5 text-xs font-medium text-student-muted',
  courseOpen: 'inline-flex shrink-0 items-center gap-1 text-sm font-bold text-student-primary',
  pagination: 'flex flex-wrap items-center justify-center gap-3',
  paginationButton: 'student-press inline-flex min-h-11 cursor-pointer items-center gap-1.5 rounded-2xl border border-student-line bg-student-surface px-4 text-sm font-bold text-student-primary-strong outline-none hover:bg-student-surface-muted focus-visible:ring-4 focus-visible:ring-student-primary/15 disabled:cursor-not-allowed disabled:opacity-45',
  paginationStatus: 'text-sm font-semibold text-student-muted',
  courseCta: 'student-press inline-flex min-h-12 cursor-not-allowed items-center justify-center gap-2 rounded-2xl bg-student-primary/40 px-5 text-sm font-bold text-white opacity-75',
  courseDetailSection: 'rounded-3xl border border-student-line bg-student-surface p-5 shadow-[0_14px_36px_-22px_rgba(49,46,129,0.42)] sm:p-7',
  sectionTitle: 'font-student-display text-2xl font-bold tracking-[-0.02em] text-student-ink',
  sectionIcon: 'text-student-primary',
  galleryButton: 'student-press absolute top-1/2 grid size-11 -translate-y-1/2 cursor-pointer place-items-center rounded-2xl bg-student-surface/90 text-student-primary-strong shadow-[0_8px_22px_-12px_rgba(49,46,129,0.6)] outline-none hover:bg-student-surface focus-visible:ring-4 focus-visible:ring-student-primary/20',
  description: 'max-w-3xl text-[15px] leading-7 text-student-muted [&_a]:cursor-pointer [&_a]:font-semibold [&_a]:text-student-primary [&_a]:underline [&_img]:my-4 [&_img]:max-w-full [&_img]:rounded-2xl [&_p+p]:mt-3 [&_ul]:my-3 [&_ul]:list-disc [&_ul]:pl-5',
  lessonPreview: 'flex min-h-12 items-center gap-3 rounded-2xl border border-student-line bg-student-surface-muted/45 px-4 py-3 text-sm font-semibold text-student-ink',
  lessonNumber: 'font-student-display text-xs font-bold text-student-primary',
  catalogCard: 'grid overflow-hidden rounded-3xl border border-student-line bg-student-surface shadow-[0_14px_36px_-22px_rgba(49,46,129,0.42)]',
  catalogStatus: 'w-fit rounded-full bg-student-bookmark/18 px-2.5 py-1 text-xs font-bold text-student-ink',
  catalogEnrollButton: 'student-press inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-2xl bg-student-primary px-4 text-sm font-bold text-white outline-none hover:bg-student-primary-strong focus-visible:ring-4 focus-visible:ring-student-primary/20 disabled:cursor-not-allowed disabled:opacity-55',
  profileLabel: 'text-sm font-medium text-student-muted',
  profileValue: 'break-words font-student-display text-base font-bold text-student-ink',
}
