export const studentUi = {
  page: 'min-h-svh overflow-x-hidden bg-student-canvas font-student-sans text-student-ink',
  shell: 'mx-auto flex min-h-svh w-full max-w-6xl flex-col px-4 py-4 sm:px-6 sm:py-6',
  topbar: 'mb-8 flex min-h-11 items-center justify-between gap-4',
  brand: 'font-student-display text-lg font-bold tracking-tight text-student-primary-strong',
  brandMark: 'grid size-10 place-items-center rounded-2xl bg-student-primary text-white',
  skipLink: 'sr-only rounded-xl bg-student-primary px-4 py-2 font-semibold text-white focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-10 focus-visible:ring-4 focus-visible:ring-student-primary/20',
  title: 'font-student-display text-3xl font-bold tracking-[-0.03em] text-student-ink sm:text-4xl',
  eyebrow: 'font-student-display text-sm font-semibold text-student-primary',
  body: 'text-[15px] leading-6 text-student-muted',
  caption: 'text-[13px] leading-5 text-student-subtle',
  card: 'rounded-3xl border border-student-line bg-student-surface shadow-[0_14px_36px_-22px_rgba(49,46,129,0.42)]',
  cardMuted: 'rounded-3xl border border-student-line bg-student-surface-muted/50',
  buttonPrimary: 'bg-student-primary text-white hover:bg-student-primary-strong focus-visible:ring-student-primary',
  buttonBookmark: 'bg-student-bookmark text-student-ink hover:bg-student-bookmark/85 focus-visible:ring-student-bookmark',
  buttonQuiet: 'bg-student-surface text-student-primary-strong hover:bg-student-surface-muted focus-visible:ring-student-primary',
  control: 'student-control min-h-11 w-full rounded-2xl border border-student-line bg-student-control px-3.5 text-[16px] text-student-ink outline-none transition-[border-color,box-shadow] duration-150 placeholder:text-student-subtle focus:border-student-primary focus-visible:ring-4 focus-visible:ring-student-primary/15 disabled:cursor-not-allowed disabled:opacity-60',
  controlInvalid: 'border-student-danger focus:border-student-danger focus-visible:ring-student-danger/15',
  label: 'font-student-display text-sm font-semibold text-student-ink',
  error: 'text-sm font-medium text-student-danger',
  link: 'font-semibold text-student-primary underline decoration-student-primary/30 underline-offset-4 hover:decoration-student-primary',
  complete: 'bg-student-complete/12 text-student-complete',
  current: 'bg-student-primary/12 text-student-primary-strong',
  next: 'bg-student-bookmark/18 text-student-ink',
  emptyIcon: 'grid size-12 place-items-center rounded-2xl bg-student-bookmark/18 text-student-ink',
  emptyTitle: 'font-student-display text-xl font-bold text-student-ink',
  loadingIcon: 'text-student-primary',
  progressRing: 'grid size-24 place-items-center rounded-full border-8 border-student-primary/15 bg-student-surface',
  progressValue: 'font-student-display text-2xl font-bold text-student-primary-strong',
  trailItem: 'flex items-center gap-3 rounded-2xl border border-student-line bg-student-surface px-4 py-3',
  trailTitle: 'truncate font-student-display text-sm font-bold text-student-ink',
}
