#!/bin/sh
set -eu

export MYSQL_PWD="$MYSQL_ROOT_PASSWORD"

mysql --protocol=tcp --host=mysql --user=root <<SQL
CREATE DATABASE IF NOT EXISTS \`${COURSE_DB_NAME}\`;
CREATE DATABASE IF NOT EXISTS \`${STUDENT_DB_NAME}\`;
CREATE DATABASE IF NOT EXISTS \`${MEDIA_DB_NAME}\`;
CREATE DATABASE IF NOT EXISTS \`${NOTIFICATION_DB_NAME}\`;

CREATE USER IF NOT EXISTS '${COURSE_DB_USER}'@'%' IDENTIFIED BY '${COURSE_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${STUDENT_DB_USER}'@'%' IDENTIFIED BY '${STUDENT_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${MEDIA_DB_USER}'@'%' IDENTIFIED BY '${MEDIA_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${NOTIFICATION_DB_USER}'@'%' IDENTIFIED BY '${NOTIFICATION_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${COURSE_DB_NAME}\`.* TO '${COURSE_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${STUDENT_DB_NAME}\`.* TO '${STUDENT_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${MEDIA_DB_NAME}\`.* TO '${MEDIA_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${NOTIFICATION_DB_NAME}\`.* TO '${NOTIFICATION_DB_USER}'@'%';
FLUSH PRIVILEGES;
SQL
