export const MEDIA_COPY = {
  file: 'File',
  mediaType: 'Loại media',
  uploadedByType: 'Actor type',
  uploadedBy: 'Actor ID',
  upload: 'Upload media',
  directUpload: 'Direct upload',
  directUploadAction: 'Upload trực tiếp',
  directUploadDescription: 'Tính checksum tại trình duyệt, truyền thẳng tới storage, rồi finalize qua Media Service.',
  directEmptyHint: 'Chọn file để bắt đầu. Reload hoặc Reset sẽ hủy và xóa toàn bộ tiến trình hiện tại.',
  checksum: 'Checksum',
  finalize: 'Finalize',
  result: 'Media đã tạo',
  empty: 'Chưa upload',
  emptyHint: 'Chọn file và Gọi API. Reset xóa kết quả, không tự POST.',
  failed: 'Upload thất bại',
  location: 'Location',
  contentUrl: 'contentUrl',
  thumbnailStatus: 'thumbnailStatus',
  thumbnail: 'Thumbnail',
  thumbnailProcessing: 'Đang tạo thumbnail, trạng thái được cập nhật tự động.',
  thumbnailFailed: 'Tạo thumbnail thất bại.',
  retry: 'Thử lại',
  loadingImage: 'Đang tải ảnh',
  imageUnavailable: 'Không thể tải ảnh',
}
