export const UI_LABELS = {
  all: 'Tất cả',
  loading: 'Đang tải',
  previous: 'Trang trước',
  next: 'Trang sau',
  firstPage: 'Trang đầu',
  lastPage: 'Trang cuối',
  page: 'Trang',
  pageSize: 'Mỗi trang',
  items: 'mục',
  select: 'Chọn',
  service: 'Service',
  input: 'Input',
  output: 'Output',
  menu: 'Menu',
  umlSuccess: 'Success — luồng chính',
  umlIdle: 'Chưa gọi API',
  callApi: 'Gọi API',
  nullable: 'Có thể null',
  notNull: 'Không null',
  optional: 'Không bắt buộc',
  requiredField: 'Bắt buộc',
  defaultValue: 'Mặc định',
  allowlist: 'Allowlist',
  queryOnly: 'GET không có request body. Chỉ gửi query trong allowlist.',
  noFilter: 'Không lọc',
  omitDefault: 'Bỏ trống = không gửi',
  reset: '',
}
