<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AdminService.Application\AdminService.Application.csproj" />
    <ProjectReference Include="..\AdminService.Infrastructure\AdminService.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup><Content Include="..\AdminService.Infrastructure\Database\Migrations\*.sql" Link="Database\Migrations\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
</Project>
