import { useEffect, useRef } from 'react'
import { Pause, Play, RotateCcw } from 'lucide-react'
import { useLocation } from 'react-router-dom'
import { Button } from '@/components/ui/Button'
import { EmptyState } from '@/components/ui/EmptyState'
import { Icon } from '@/components/ui/Icon'
import { LoadingState } from '@/components/ui/LoadingState'
import { PageHeader } from '@/components/ui/PageHeader'
import { InputPanel } from '@/components/layout/InputPanel'
import { OutputPanel } from '@/components/layout/OutputPanel'
import { Workbench } from '@/components/layout/Workbench'
import { GET_NOTIFICATION_BATCH_ACTIVITY } from '@/constants/activities/getNotificationBatch'
import { NOTIFICATION_BATCH_STATUS } from '@/constants/notification'
import { UI_LABELS } from '@/constants/ui'
import { useNotificationBatchProgress } from '@/hooks/notifications/useNotificationBatchProgress'
import { ui } from '@/theme'
import { NotificationBatchProgressForm } from './components/NotificationBatchProgressForm'
import { NotificationBatchProgressManualForm } from './components/NotificationBatchProgressManualForm'

const statusTone = { [NOTIFICATION_BATCH_STATUS.completed]: ui.badgeSuccess, [NOTIFICATION_BATCH_STATUS.partialFailed]: ui.badgeWarning, [NOTIFICATION_BATCH_STATUS.failed]: ui.badgeDanger }
function statusClass(status) { return statusTone[status] ?? ui.badgeMuted }
function percent(batch) { if (!batch?.totalCount) return 0; return Math.min(100, Math.round((batch.processedCount / batch.totalCount) * 100)) }
function outputJson(progress) { return progress.error ? { data: null, error: progress.error, meta: { traceId: progress.traceId, query: progress.query } } : { data: progress.data, meta: { traceId: progress.traceId, query: progress.query, paused: progress.paused }, success: progress.success } }

function BatchProgressView({ progress }) {
  const batch = progress.data; const progressPercent = percent(batch)
  if (!batch) return <EmptyState title="Chưa chọn batch" description="Dán Batch ID để bắt đầu theo dõi tiến trình gửi." />
  return <div className="space-y-5"><section className={`${ui.rail} rounded-lg ${ui.card} p-5`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className={`font-display text-[22px] font-semibold ${ui.title}`}>{batch.status === NOTIFICATION_BATCH_STATUS.snapshotting ? 'Đang chụp danh sách học viên' : `${progressPercent}% đã xử lý`}</p><p className={`mt-1 text-[14px] ${ui.body}`}>{progress.isTerminal ? 'Batch đã đạt trạng thái cuối, polling đã tự dừng.' : progress.paused ? 'Polling đang pause tại trình duyệt.' : 'Đang cập nhật tự động mỗi 3 giây.'}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-medium ${statusClass(batch.status)}`}>{batch.status}</span></div><div className={`mt-5 h-3 overflow-hidden rounded-full ${ui.toastBarTrack}`} role="progressbar" aria-valuenow={progressPercent} aria-valuemin="0" aria-valuemax="100"><div className={`${batch.failedCount > 0 ? ui.toastBarError : ui.toastBarSuccess} h-full rounded-full transition-[width] duration-200 ease-[cubic-bezier(0.23,1,0.32,1)]`} style={{ width: `${progressPercent}%` }} /></div><div className="mt-3 flex justify-between font-mono text-[12px] tabular-nums"><span className={ui.caption}>{batch.totalCount ? `${batch.processedCount.toLocaleString()} / ${batch.totalCount.toLocaleString()} người nhận` : 'Đang chờ snapshot trả total count'}</span><span className={ui.caption}>chunk {batch.batchSize}</span></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Metric label="Đã gửi" value={batch.successCount} tone={ui.badgeSuccess} /><Metric label="Thất bại" value={batch.failedCount} tone={batch.failedCount ? ui.badgeDanger : ui.badgeMuted} /><Metric label="Còn lại" value={Math.max(0, batch.totalCount - batch.processedCount)} tone={ui.badgeMuted} /></div></section><section className={`rounded-lg ${ui.card} p-5`}><div className="flex items-center justify-between gap-3"><div><p className={`text-[13px] font-medium ${ui.title}`}>Kiểm soát polling</p><p className={`mt-1 text-[12px] ${ui.body}`}>{progress.isTerminal ? 'Không cần gọi lại API sau khi Worker hoàn tất.' : 'Pause giữ nguyên dữ liệu trên màn hình; tiếp tục gọi lại ngay.'}</p></div>{!progress.isTerminal ? progress.paused ? <Button onClick={progress.resume}><Icon icon={Play} />Tiếp tục</Button> : <Button variant="ghost" onClick={progress.pause}><Icon icon={Pause} />Pause</Button> : null}</div></section>{batch.failedCount > 0 ? <Failures progress={progress} /> : null}</div>
}
function Metric({ label, value, tone }) { return <div className={`rounded-md px-2 py-3 ${tone}`}><p className="font-mono text-[20px] font-semibold tabular-nums">{value.toLocaleString()}</p><p className="mt-1 text-[11px] font-medium">{label}</p></div> }
function Failures({ progress }) { return <section className={`rounded-lg ${ui.card} p-5`}><div className="flex items-baseline justify-between gap-3"><div><p className={`font-display text-[18px] font-semibold ${ui.title}`}>Lỗi theo người nhận</p><p className={`mt-1 text-[13px] ${ui.body}`}>Chỉ hiển thị sau khi batch ở trạng thái cuối.</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-medium ${ui.badgeDanger}`}>{progress.data.failedCount} lỗi</span></div>{progress.failuresLoading ? <div className="mt-4"><LoadingState /></div> : null}{progress.failuresError ? <p className={`mt-4 rounded-md ${ui.badgeDanger} px-3 py-2 text-[13px]`}>{progress.failuresError.code}: {progress.failuresError.message}</p> : null}{!progress.failuresLoading && !progress.failuresError && progress.failures.length ? <div className="mt-4 overflow-hidden rounded-md border border-line"><table className="w-full text-left text-[13px]"><thead className={ui.tableHead}><tr><th className="px-3 py-2 font-medium">Student ID</th><th className="px-3 py-2 font-medium">Retry</th><th className="px-3 py-2 font-medium">Lỗi cuối</th></tr></thead><tbody>{progress.failures.map((item) => <tr key={item.studentId} className={ui.tableRow}><td className="break-all px-3 py-2 font-mono text-[11px]">{item.studentId}</td><td className="px-3 py-2 font-mono tabular-nums">{item.retryCount}</td><td className="px-3 py-2">{item.errorMessage}</td></tr>)}</tbody></table></div> : null}</section> }

export function NotificationBatchProgressPage() {
  const progress = useNotificationBatchProgress(); const location = useLocation(); const didReadRouteState = useRef(false)
  useEffect(() => { if (!didReadRouteState.current && location.state?.batchId) { didReadRouteState.current = true; progress.watch(location.state.batchId) } }, [location.state?.batchId, progress])
  return <Workbench input={<InputPanel actions={<Button variant="ghost" disabled={progress.loading} onClick={progress.reset}><Icon icon={RotateCcw} />{UI_LABELS.reset}</Button>} guided={<div className="flex h-full min-h-0 flex-col"><div className="shrink-0 px-5 pt-4"><PageHeader eyebrow="Notification · monitor" title="Tiến trình gửi hàng loạt" description="Theo dõi Worker theo batch. Dữ liệu mới chỉ thay thế sau mỗi lần GET thành công." /></div><div className="min-h-0 flex-1"><NotificationBatchProgressForm query={progress.query} loading={progress.loading} onChange={progress.setQuery} onSubmit={() => progress.watch(progress.query.batchId)} /></div></div>} manual={<NotificationBatchProgressManualForm query={progress.query} loading={progress.loading} onChange={progress.setQuery} onSubmit={() => progress.watch(progress.query.batchId)} />} />} output={<OutputPanel json={outputJson(progress)} activity={GET_NOTIFICATION_BATCH_ACTIVITY} run={{ loading: progress.loading, success: progress.success, error: progress.error }}>{progress.error ? <EmptyState title="Không đọc được tiến trình" description={`${progress.error.code}: ${progress.error.message}`} /> : <BatchProgressView progress={progress} />}</OutputPanel>} />
}
