import { POST_MEDIA_DEFAULT_QUERY, POST_MEDIA_INPUT_FIELDS } from '@/constants/inputs/postMedia'

export const POST_MEDIA_DIRECT_DEFAULT_QUERY = POST_MEDIA_DEFAULT_QUERY
export const POST_MEDIA_DIRECT_INPUT_FIELDS = POST_MEDIA_INPUT_FIELDS
