import { ACTIVITY_NODE_KIND } from '@/constants/activity'
import { API_ERROR_CODES } from '@/constants/apiErrorCodes'
import { API_ROUTES } from '@/constants/apiRoutes'
import { HTTP_STATUS } from '@/constants/http'

export const GET_STUDENTS_ACTIVITY = {
  id: 'getStudents',
  title: 'Liệt kê Học viên',
  method: 'GET',
  path: API_ROUTES.students.list,
  lanes: ['Client', 'Gateway', 'Student Service', 'Repository', 'MySQL', 'Fault'],
  nodes: [
    {
      id: 'start',
      kind: ACTIVITY_NODE_KIND.start,
      label: '',
      lane: 0,
      row: 0,
    },
    {
      id: 'client',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'GET query filters',
      lane: 0,
      row: 1,
    },
    {
      id: 'networkError',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'NETWORK_ERROR',
      lane: 5,
      row: 1,
    },
    {
      id: 'gateway',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'Forward query',
      lane: 1,
      row: 2,
    },
    {
      id: 'timeout',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'REQUEST_TIMEOUT',
      lane: 5,
      row: 2,
    },
    {
      id: 'serviceUnavailable',
      kind: ACTIVITY_NODE_KIND.action,
      label: '503 SERVICE_UNAVAILABLE',
      lane: 5,
      row: 3,
    },
    {
      id: 'validate',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'Validate, normalize, defaults',
      lane: 2,
      row: 3,
    },
    {
      id: 'queryValid',
      kind: ACTIVITY_NODE_KIND.decision,
      label: 'Query hợp lệ?',
      lane: 2,
      row: 4,
    },
    {
      id: 'validationFailed',
      kind: ACTIVITY_NODE_KIND.action,
      label: '400 VALIDATION_FAILED',
      lane: 5,
      row: 4,
    },
    {
      id: 'unexpected',
      kind: ACTIVITY_NODE_KIND.action,
      label: '500 UNEXPECTED_ERROR',
      lane: 5,
      row: 5,
    },
    {
      id: 'repo',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'Count + page ổn định',
      lane: 3,
      row: 5,
    },
    {
      id: 'db',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'SELECT students',
      lane: 4,
      row: 6,
    },
    {
      id: 'dbUnavailable',
      kind: ACTIVITY_NODE_KIND.action,
      label: '503 DATABASE_UNAVAILABLE',
      lane: 5,
      row: 6,
    },
    {
      id: 'ok',
      kind: ACTIVITY_NODE_KIND.action,
      label: '200 data + meta.pagination',
      lane: 2,
      row: 7,
    },
    {
      id: 'respond',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'HTTP response',
      lane: 1,
      row: 8,
    },
    {
      id: 'endOk',
      kind: ACTIVITY_NODE_KIND.end,
      label: 'Success',
      lane: 0,
      row: 9,
    },
    {
      id: 'endFail',
      kind: ACTIVITY_NODE_KIND.end,
      label: 'Fail',
      lane: 5,
      row: 9,
    },
  ],
  edges: [
    { from: 'start', to: 'client' },
    { from: 'client', to: 'gateway' },
    {
      from: 'client',
      to: 'networkError',
      guard: 'Mất kết nối',
      outcome: 'fail',
    },
    { from: 'networkError', to: 'endFail', outcome: 'fail' },
    { from: 'gateway', to: 'validate' },
    {
      from: 'gateway',
      to: 'timeout',
      guard: 'Hết timeout',
      outcome: 'fail',
    },
    { from: 'timeout', to: 'endFail', outcome: 'fail' },
    {
      from: 'gateway',
      to: 'serviceUnavailable',
      guard: 'Hạ nguồn down',
      outcome: 'fail',
    },
    { from: 'serviceUnavailable', to: 'endFail', outcome: 'fail' },
    { from: 'validate', to: 'queryValid' },
    {
      from: 'validate',
      to: 'unexpected',
      guard: 'Lỗi chưa xử lý',
      outcome: 'fail',
    },
    { from: 'unexpected', to: 'endFail', outcome: 'fail' },
    {
      from: 'queryValid',
      to: 'validationFailed',
      guard: 'Không',
      outcome: 'fail',
    },
    { from: 'validationFailed', to: 'endFail', outcome: 'fail' },
    { from: 'queryValid', to: 'repo', guard: 'Có' },
    { from: 'repo', to: 'db' },
    {
      from: 'db',
      to: 'dbUnavailable',
      guard: 'Không',
      outcome: 'fail',
    },
    { from: 'dbUnavailable', to: 'endFail', outcome: 'fail' },
    { from: 'db', to: 'ok', guard: 'Có' },
    { from: 'ok', to: 'respond' },
    { from: 'respond', to: 'endOk' },
  ],
  pendingPath: ['start', 'client', 'gateway'],
  successPath: [
    'start',
    'client',
    'gateway',
    'validate',
    'queryValid',
    'repo',
    'db',
    'ok',
    'respond',
    'endOk',
  ],
  failByCode: {
    [API_ERROR_CODES.networkError]: {
      node: 'networkError',
      path: ['start', 'client', 'networkError', 'endFail'],
    },
    [API_ERROR_CODES.requestTimeout]: {
      node: 'timeout',
      path: ['start', 'client', 'gateway', 'timeout', 'endFail'],
    },
    [API_ERROR_CODES.serviceUnavailable]: {
      node: 'serviceUnavailable',
      path: ['start', 'client', 'gateway', 'serviceUnavailable', 'endFail'],
    },
    [API_ERROR_CODES.validationFailed]: {
      node: 'validationFailed',
      path: [
        'start',
        'client',
        'gateway',
        'validate',
        'queryValid',
        'validationFailed',
        'endFail',
      ],
    },
    [API_ERROR_CODES.unexpectedError]: {
      node: 'unexpected',
      path: ['start', 'client', 'gateway', 'validate', 'unexpected', 'endFail'],
    },
    [API_ERROR_CODES.databaseUnavailable]: {
      node: 'dbUnavailable',
      path: [
        'start',
        'client',
        'gateway',
        'validate',
        'queryValid',
        'repo',
        'db',
        'dbUnavailable',
        'endFail',
      ],
    },
    [API_ERROR_CODES.dependencyUnavailable]: {
      node: 'dbUnavailable',
      path: [
        'start',
        'client',
        'gateway',
        'validate',
        'queryValid',
        'repo',
        'db',
        'dbUnavailable',
        'endFail',
      ],
    },
    default: {
      node: 'unexpected',
      path: ['start', 'client', 'gateway', 'validate', 'unexpected', 'endFail'],
    },
  },
  notes: {
    empty: `${HTTP_STATUS.ok} + data [] không phải lỗi; không có nhánh 404.`,
  },
}
