import { ACTIVITY_NODE_KIND } from '@/constants/activity'
import { API_ERROR_CODES } from '@/constants/apiErrorCodes'
import { API_ROUTES } from '@/constants/apiRoutes'

export const POST_MEDIA_DIRECT_ACTIVITY = {
  id: 'postMediaDirect',
  title: 'Direct upload media',
  method: 'POST × 3',
  path: API_ROUTES.media.uploadIntents,
  lanes: ['Client', 'Web Worker', 'Gateway', 'Media Service', 'MinIO', 'Fault'],
  nodes: [
    { id: 'start', kind: ACTIVITY_NODE_KIND.start, label: '', lane: 0, row: 0 },
    { id: 'validate', kind: ACTIVITY_NODE_KIND.action, label: 'Validate file', lane: 0, row: 1 },
    { id: 'hash', kind: ACTIVITY_NODE_KIND.action, label: 'SHA-256 chunks', lane: 1, row: 2 },
    { id: 'intent', kind: ACTIVITY_NODE_KIND.action, label: 'POST upload-intents', lane: 2, row: 3 },
    { id: 'pending', kind: ACTIVITY_NODE_KIND.action, label: 'PENDING + signed form', lane: 3, row: 4 },
    { id: 'upload', kind: ACTIVITY_NODE_KIND.action, label: 'XHR signed POST', lane: 4, row: 5 },
    { id: 'complete', kind: ACTIVITY_NODE_KIND.action, label: 'POST upload-complete', lane: 2, row: 6 },
    { id: 'ready', kind: ACTIVITY_NODE_KIND.action, label: 'Verify + READY draft', lane: 3, row: 7 },
    { id: 'endOk', kind: ACTIVITY_NODE_KIND.end, label: 'Success', lane: 0, row: 8 },
    { id: 'clientError', kind: ACTIVITY_NODE_KIND.action, label: 'INVALID_MEDIA', lane: 5, row: 2 },
    { id: 'networkError', kind: ACTIVITY_NODE_KIND.action, label: 'NETWORK_ERROR', lane: 5, row: 4 },
    { id: 'uploadError', kind: ACTIVITY_NODE_KIND.action, label: 'DIRECT_UPLOAD_FAILED', lane: 5, row: 6 },
    { id: 'unexpected', kind: ACTIVITY_NODE_KIND.action, label: 'UNEXPECTED_ERROR', lane: 5, row: 8 },
    { id: 'endFail', kind: ACTIVITY_NODE_KIND.end, label: 'Fail', lane: 5, row: 9 },
  ],
  edges: [
    { from: 'start', to: 'validate' },
    { from: 'validate', to: 'hash', guard: 'Hợp lệ' },
    { from: 'validate', to: 'clientError', guard: 'Sai file', outcome: 'fail' },
    { from: 'clientError', to: 'endFail', outcome: 'fail' },
    { from: 'hash', to: 'intent' },
    { from: 'intent', to: 'pending' },
    { from: 'intent', to: 'networkError', guard: 'API lỗi', outcome: 'fail' },
    { from: 'networkError', to: 'endFail', outcome: 'fail' },
    { from: 'pending', to: 'upload' },
    { from: 'upload', to: 'complete' },
    { from: 'upload', to: 'uploadError', guard: 'MinIO lỗi', outcome: 'fail' },
    { from: 'uploadError', to: 'endFail', outcome: 'fail' },
    { from: 'complete', to: 'ready' },
    { from: 'complete', to: 'unexpected', guard: 'Finalize lỗi', outcome: 'fail' },
    { from: 'unexpected', to: 'endFail', outcome: 'fail' },
    { from: 'ready', to: 'endOk' },
  ],
  pendingPath: ['start', 'validate'],
  successPath: ['start', 'validate', 'hash', 'intent', 'pending', 'upload', 'complete', 'ready', 'endOk'],
  failByCode: {
    [API_ERROR_CODES.invalidMedia]: { node: 'clientError', path: ['start', 'validate', 'clientError', 'endFail'] },
    [API_ERROR_CODES.unsupportedMediaType]: { node: 'clientError', path: ['start', 'validate', 'clientError', 'endFail'] },
    [API_ERROR_CODES.payloadTooLarge]: { node: 'clientError', path: ['start', 'validate', 'clientError', 'endFail'] },
    [API_ERROR_CODES.networkError]: { node: 'networkError', path: ['start', 'validate', 'hash', 'intent', 'networkError', 'endFail'] },
    [API_ERROR_CODES.requestTimeout]: { node: 'networkError', path: ['start', 'validate', 'hash', 'intent', 'networkError', 'endFail'] },
    [API_ERROR_CODES.serviceUnavailable]: { node: 'networkError', path: ['start', 'validate', 'hash', 'intent', 'networkError', 'endFail'] },
    [API_ERROR_CODES.directUploadFailed]: { node: 'uploadError', path: ['start', 'validate', 'hash', 'intent', 'pending', 'upload', 'uploadError', 'endFail'] },
    [API_ERROR_CODES.unexpectedError]: { node: 'unexpected', path: ['start', 'validate', 'hash', 'intent', 'pending', 'upload', 'complete', 'unexpected', 'endFail'] },
  },
}
