import { ACTIVITY_NODE_KIND } from '@/constants/activity'
import { API_ERROR_CODES } from '@/constants/apiErrorCodes'
import { API_ROUTES } from '@/constants/apiRoutes'
import { HTTP_STATUS } from '@/constants/http'

export const POST_MEDIA_ACTIVITY = {
  id: 'postMedia',
  title: 'Upload media',
  method: 'POST',
  path: API_ROUTES.media.upload,
  lanes: [
    'Client',
    'Gateway',
    'Media Service',
    'Student Service',
    'MySQL',
    'MinIO',
    'Fault',
  ],
  nodes: [
    { id: 'start', kind: ACTIVITY_NODE_KIND.start, label: '', lane: 0, row: 0 },
    {
      id: 'client',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'POST multipart',
      lane: 0,
      row: 1,
    },
    {
      id: 'networkError',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'NETWORK_ERROR',
      lane: 6,
      row: 1,
    },
    {
      id: 'gateway',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'Forward upload',
      lane: 1,
      row: 2,
    },
    {
      id: 'timeout',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'REQUEST_TIMEOUT',
      lane: 6,
      row: 2,
    },
    {
      id: 'payloadTooLarge',
      kind: ACTIVITY_NODE_KIND.action,
      label: '413 PAYLOAD_TOO_LARGE',
      lane: 6,
      row: 3,
    },
    {
      id: 'serviceUnavailable',
      kind: ACTIVITY_NODE_KIND.action,
      label: '503 SERVICE_UNAVAILABLE',
      lane: 6,
      row: 4,
    },
    {
      id: 'validate',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'Validate multipart',
      lane: 2,
      row: 3,
    },
    {
      id: 'invalidMedia',
      kind: ACTIVITY_NODE_KIND.action,
      label: '400 INVALID_MEDIA',
      lane: 6,
      row: 5,
    },
    {
      id: 'invalidActor',
      kind: ACTIVITY_NODE_KIND.action,
      label: '400 INVALID_ACTOR_TYPE',
      lane: 6,
      row: 6,
    },
    {
      id: 'unsupportedType',
      kind: ACTIVITY_NODE_KIND.action,
      label: '415 UNSUPPORTED_MEDIA_TYPE',
      lane: 6,
      row: 7,
    },
    {
      id: 'verifyActor',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'Verify uploadedBy',
      lane: 3,
      row: 4,
    },
    {
      id: 'actorNotFound',
      kind: ACTIVITY_NODE_KIND.action,
      label: '404 ACTOR_NOT_FOUND',
      lane: 6,
      row: 8,
    },
    {
      id: 'studentDown',
      kind: ACTIVITY_NODE_KIND.action,
      label: '503 STUDENT_SERVICE_UNAVAILABLE',
      lane: 6,
      row: 9,
    },
    {
      id: 'insertPending',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'Insert media PENDING',
      lane: 4,
      row: 5,
    },
    {
      id: 'uploadMinio',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'Stream + SHA-256',
      lane: 5,
      row: 6,
    },
    {
      id: 'uploadFailed',
      kind: ACTIVITY_NODE_KIND.action,
      label: '503 MEDIA_UPLOAD_FAILED',
      lane: 6,
      row: 10,
    },
    {
      id: 'markReady',
      kind: ACTIVITY_NODE_KIND.action,
      label: 'READY + thumbnail job',
      lane: 4,
      row: 7,
    },
    {
      id: 'unexpected',
      kind: ACTIVITY_NODE_KIND.action,
      label: '500 UNEXPECTED_ERROR',
      lane: 6,
      row: 11,
    },
    {
      id: 'respond',
      kind: ACTIVITY_NODE_KIND.action,
      label: '201 Location',
      lane: 1,
      row: 8,
    },
    {
      id: 'endOk',
      kind: ACTIVITY_NODE_KIND.end,
      label: 'Success',
      lane: 0,
      row: 9,
    },
    {
      id: 'endFail',
      kind: ACTIVITY_NODE_KIND.end,
      label: 'Fail',
      lane: 6,
      row: 12,
    },
  ],
  edges: [
    { from: 'start', to: 'client' },
    { from: 'client', to: 'gateway' },
    { from: 'client', to: 'networkError', guard: 'Mất kết nối', outcome: 'fail' },
    { from: 'networkError', to: 'endFail', outcome: 'fail' },
    { from: 'gateway', to: 'validate' },
    { from: 'gateway', to: 'timeout', guard: 'Hết timeout', outcome: 'fail' },
    { from: 'timeout', to: 'endFail', outcome: 'fail' },
    {
      from: 'gateway',
      to: 'payloadTooLarge',
      guard: 'Vượt giới hạn',
      outcome: 'fail',
    },
    { from: 'payloadTooLarge', to: 'endFail', outcome: 'fail' },
    {
      from: 'gateway',
      to: 'serviceUnavailable',
      guard: 'Hạ nguồn down',
      outcome: 'fail',
    },
    { from: 'serviceUnavailable', to: 'endFail', outcome: 'fail' },
    { from: 'validate', to: 'verifyActor', guard: 'Hợp lệ' },
    { from: 'validate', to: 'invalidMedia', guard: 'Sai field/file', outcome: 'fail' },
    { from: 'invalidMedia', to: 'endFail', outcome: 'fail' },
    { from: 'validate', to: 'invalidActor', guard: 'Sai actor type', outcome: 'fail' },
    { from: 'invalidActor', to: 'endFail', outcome: 'fail' },
    { from: 'validate', to: 'unsupportedType', guard: 'MIME lệch', outcome: 'fail' },
    { from: 'unsupportedType', to: 'endFail', outcome: 'fail' },
    { from: 'verifyActor', to: 'insertPending', guard: 'Tồn tại' },
    { from: 'verifyActor', to: 'actorNotFound', guard: 'Không có', outcome: 'fail' },
    { from: 'actorNotFound', to: 'endFail', outcome: 'fail' },
    {
      from: 'verifyActor',
      to: 'studentDown',
      guard: 'Student down',
      outcome: 'fail',
    },
    { from: 'studentDown', to: 'endFail', outcome: 'fail' },
    { from: 'insertPending', to: 'uploadMinio' },
    { from: 'uploadMinio', to: 'markReady', guard: 'Có' },
    { from: 'uploadMinio', to: 'uploadFailed', guard: 'Không', outcome: 'fail' },
    { from: 'uploadFailed', to: 'endFail', outcome: 'fail' },
    { from: 'markReady', to: 'respond' },
    { from: 'markReady', to: 'unexpected', guard: 'DB lỗi', outcome: 'fail' },
    { from: 'unexpected', to: 'endFail', outcome: 'fail' },
    { from: 'respond', to: 'endOk' },
  ],
  pendingPath: ['start', 'client', 'gateway'],
  successPath: [
    'start',
    'client',
    'gateway',
    'validate',
    'verifyActor',
    'insertPending',
    'uploadMinio',
    'markReady',
    'respond',
    'endOk',
  ],
  failByCode: {
    [API_ERROR_CODES.networkError]: {
      node: 'networkError',
      path: ['start', 'client', 'networkError', 'endFail'],
    },
    [API_ERROR_CODES.requestTimeout]: {
      node: 'timeout',
      path: ['start', 'client', 'gateway', 'timeout', 'endFail'],
    },
    [API_ERROR_CODES.payloadTooLarge]: {
      node: 'payloadTooLarge',
      path: ['start', 'client', 'gateway', 'payloadTooLarge', 'endFail'],
    },
    [API_ERROR_CODES.serviceUnavailable]: {
      node: 'serviceUnavailable',
      path: ['start', 'client', 'gateway', 'serviceUnavailable', 'endFail'],
    },
    [API_ERROR_CODES.invalidMedia]: {
      node: 'invalidMedia',
      path: ['start', 'client', 'gateway', 'validate', 'invalidMedia', 'endFail'],
    },
    [API_ERROR_CODES.invalidActorType]: {
      node: 'invalidActor',
      path: ['start', 'client', 'gateway', 'validate', 'invalidActor', 'endFail'],
    },
    [API_ERROR_CODES.unsupportedMediaType]: {
      node: 'unsupportedType',
      path: [
        'start',
        'client',
        'gateway',
        'validate',
        'unsupportedType',
        'endFail',
      ],
    },
    [API_ERROR_CODES.actorNotFound]: {
      node: 'actorNotFound',
      path: [
        'start',
        'client',
        'gateway',
        'validate',
        'verifyActor',
        'actorNotFound',
        'endFail',
      ],
    },
    [API_ERROR_CODES.studentServiceUnavailable]: {
      node: 'studentDown',
      path: [
        'start',
        'client',
        'gateway',
        'validate',
        'verifyActor',
        'studentDown',
        'endFail',
      ],
    },
    [API_ERROR_CODES.mediaUploadFailed]: {
      node: 'uploadFailed',
      path: [
        'start',
        'client',
        'gateway',
        'validate',
        'verifyActor',
        'insertPending',
        'uploadMinio',
        'uploadFailed',
        'endFail',
      ],
    },
    [API_ERROR_CODES.storageUnavailable]: {
      node: 'uploadFailed',
      path: [
        'start',
        'client',
        'gateway',
        'validate',
        'verifyActor',
        'insertPending',
        'uploadMinio',
        'uploadFailed',
        'endFail',
      ],
    },
    [API_ERROR_CODES.unexpectedError]: {
      node: 'unexpected',
      path: [
        'start',
        'client',
        'gateway',
        'validate',
        'verifyActor',
        'insertPending',
        'uploadMinio',
        'markReady',
        'unexpected',
        'endFail',
      ],
    },
    default: {
      node: 'unexpected',
      path: ['start', 'client', 'gateway', 'validate', 'unexpected', 'endFail'],
    },
  },
  notes: {
    empty: `${HTTP_STATUS.created} xác nhận media gốc READY. Thumbnail có thể QUEUED; Worker chạy sau response. Upload không idempotent.`,
  },
}
